### ISSUE TITLE
paper link

### ISSUE THREAD

**Issue by ChengBinJin** [th2l/Eye_VR_Segmentation#1]
@th2l 
Hi, I can't find out your paper on the internet. Do you mind to share the link of "Eye Semantic Segmentation with a Lightweight Model?"

**Comment by ChengBinJin** [comment]
@th2l 
Hi, I can't find out your paper on the internet. Do you mind to share the link of "Eye Semantic Segmentation with a Lightweight Model?"

**Comment by th2l** [comment]
Hi, You can download my paper in this link https://1drv.ms/b/s!AqId_ibU7DInmTYCOsHvcjQitGsX?e=knkqee

**Comment by ChengBinJin** [comment]
@th2l Thank you!
