### ISSUE TITLE
IndexError: index 255 is out of bounds for axis 0 with size 144

### ISSUE THREAD

**Issue by topksampler** [th2l/Eye_VR_Segmentation#2]
I am testing the model, on my own dataset, and it seems to be giving me this error. Can you help me out with the implementation.

**Comment by th2l** [comment]
Could you give me more details, which line you got errors, input size, ...?

**Comment by SjoerdTimovanVliet** [comment]
@lalith1403  What is the layout of the train directory that you used? I would also like to train the network on my own dataset. Could you give any info on how to set this up with the groundtruths and the images?

**Comment by topksampler** [comment]
I don't think I proceeded with this repository.
