### ISSUE TITLE
Could you provide the dataset?

### ISSUE THREAD

**Issue by AiJingning** [th2l/Eye_VR_Segmentation#6]
Could you provide the Open eye dataset(Open EDS)?

**Comment by th2l** [comment]
I do not have permission to provide OpenEDS dataset. You should contact the authors in the following paper to get the dataset
[Dataset for Eye Tracking on a Virtual Reality Platform](https://dl.acm.org/doi/abs/10.1145/3379155.3391317)

> Stephan Joachim Garbin, Oleg Komogortsev, Robert Cavin, Gregory Hughes, Yiru Shen, Immo Schuetz, and Sachin S Talathi. 2020. Dataset for Eye Tracking on a Virtual Reality Platform. In ACM Symposium on Eye Tracking Research and Applications (ETRA '20 Full Papers). Association for Computing Machinery, New York, NY, USA, Article 13, 1–10. DOI:https://doi.org/10.1145/3379155.3391317

**Comment by AiJingning** [comment]
thank you very much~
